- name: Slurp  private id_rsa key
  slurp:
    src: "{{ user_local_private_ssh_key_path }}"
  register: private_key

- copy: content="{{ private_key.content | b64decode }}" dest=./privkey.txt

- debug:
    msg:
    - "{{ private_key.content | b64decode }}"

- name: Create jenkins ssh credential
  uri:
    url: http://{{ jenkins_host }}/credentials/store/system/domain/_/createCredentials
    method: POST
    headers:
      Jenkins-Crumb: "{{ crumb.json.crumb }}"
    force_basic_auth: yes
    return_content: yes
    user: "{{ jenkins_user }}"
    password: "{{ jenkins_password }}"
    body: |
      json={  
        "":"0",
        "credentials":{  
          "scope":"GLOBAL",
          "id":"jenkins2",
          "description":"JENKINS SSH KEY",
          "username":"jenkins",
          "privateKeySource":{
             "value":"0",
             "privateKey":""{{ lookup('file', 'privkey.txt' ) | trim | replace('\n', '') |  replace(' ', '')}}"",
             "stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource",
             "$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource"
          },
          "passphrase":"",
          "$redact":"passphrase",
          "stapler-class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey",
          "$class":"com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"
        },
        "Jenkins-Crumb":"{{ crumb.json.crumb }}"
      }
    status_code: 302
  register: credential
